---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
class(dialogue)
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE,T)
class(aLogical)
sum(aLogical)

```


```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
class(studentMajors)
levels(studentMajors)
typeof(studentMajors)
as.integer(studentMajors)
```


```{r}
birthplace<-factor(
  c("台中市","台北市","台北市","嘉義市")
)
class(birthplace)
typeof(birthplace)
levels(birthplace)
as.integer(birthplace)

```

```{r}
stringInteger<-c("1","2","31.54")
stringInteger
class(stringInteger)


trueInteger<-as.integer(stringInteger)
trueInteger
class(trueInteger)
```


```{r}
library(lubridate)
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
dtObject
```

```{r}
class(dtObject)
typeof(dtObject)
as.double(dtObject)

Sys.timezone()
```






