---
title: '2019-06-05'
author: "spin"
date: "2019年6月5日"
output: html_document
---



```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
```

```{r}

utility_cobb_douglass(1,2,0.5,0.8)
utility_cobb_douglass(1,2,.beta=0.8,.alpha=0.5)
```

#####ch9
```{r}
load(url("https://github.com/tpemartin/github-data/blob/master/loopTranscriptData.Rda?raw=true"))
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)}
```

```{r}
gpa_fun(transcriptDataFinal$學號)


studentIds <- unique(transcriptDataFinal$學號) # 全部可能學號
studentIds
```

sequence_source
```{r}
# 以前5筆學號為sequence_source
studentIds5 <- studentIds[1:5]
studentIds5
```
作法一
```{r}
gpa_fun(studentIds5[[1]])
for(i in studentIds5){
  print(i)
  print(gpa_fun(i))
}
```
作法二
```{r}
for(i in c(1:5)){
  print(i) 
  print(studentIds5[[i]])
}
```

三.seq_along()
```{r}
for(i in seq_along(studentIds5)){
  print(i)
  print(studentIds5[[i]])
}
```
練習##
```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
gpa_fun()
```
一.
```{r}
for(i in gmailAddress){
  print(i)
}
```

二.
```{r}
for(i in c(1:4)){
  print(i)
  print(gmailAddress[[i]])
}
```
三
```{r}
for(i in seq_along(gmailAddress)){
  print(i)
  print(gmailAddress[[i]])
}
```


##範例2
```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```
任務：一一檢查gmailAddress每個元素，若沒有寫“@gmail.com”則加上
```{r}
# 開始設定
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
cat("起始狀況\n")
gmailAddress

# for loop
for(i in seq_along(gmailAddress)){
  if(!str_detect(gmailAddress[[i]],"@gmail.com")){
    correctGmailAddress <-
      str_c(gmailAddress[[i]],"@gmail.com")
    gmailAddress[[i]] <- correctGmailAddress
  }
}

cat("修正後狀況\n")
gmailAddress
```

```{r}
load(url("https://www.dropbox.com/s/qnz9paigf61yjus/commitHistory.Rda?raw=1"))
for(i in seq_along(commitHistory)){
  print(
    str_c(
      "Author is ",
      commitHistory[[i]][["commit"]][["author"]][["name"]],
      ". Committer is ",
      commitHistory[[i]][["commit"]][["committer"]][["name"]]
      )
    )
}

```
任務0：print「每個」commit的author等於committer的邏輯判斷結果。
sequence source
commitHistory
body
print「第i個」commit的author等於committer的邏輯判斷結果。
```{r}
i <- 1

(commitHistory[[i]][["commit"]][["author"]][["name"]]==commitHistory[[i]][["commit"]][["committer"]][["name"]]) -> logiResult
print(logiResult)

for(i in seq_along(commitHistory)){
  (commitHistory[[i]][["commit"]][["author"]][["name"]]==
     commitHistory[[i]][["commit"]][["committer"]][["name"]]) ->
    logiResult
  print(logiResult)  
}
```



```{r}
# 把"你好"存在saveCharacter第3個位置
saveCharacter # 儲存前
saveCharacter[[3]] <- "你好"
saveCharacter # 儲存後

```

```{r}
# 把 72.3 存在saveNumeric第3個位置
saveNumeric # 儲存前
saveNumeric[[3]] <- 72.3
saveNumeric # 儲存後

```

```{r}
# 把 TRUE 存在saveLogical第3個位置
saveLogical # 儲存前
saveLogical[[3]] <- TRUE
saveLogical # 儲存後


```

```{r}
# 把 list(姓名="小明",電話="02-86741111") 存在saveList第3個位置
saveList # 儲存前
saveList[[3]] <- list(姓名="小明",電話="02-86741111")
saveList # 儲存後
```



